name: Screenshots

on:
  pull_request:
    branches:
      - main
jobs:
  All:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run screenshot tests
      run: ./update_snapshots.sh
    - uses: jverkoey/xcresulttool@346c0fe4ea30add30b8eb3f9c6f999c2916d6cdb
      with:
        upload-bundles: never
        path: |
          TestResults/Apple Watch Series 8 (45mm).xcresult
#          TestResults/Apple Watch Series 8 (41mm).xcresult
#          TestResults/Apple Watch Ultra (49mm).xcresult
      if: success() || failure()
