name: Swift

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Run_workspace_Tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: xcodebuild test -scheme Watch -project ElectricSidecar/ElectricSidecar.xcodeproj -destination 'platform=WatchOS Simulator,name=Apple Watch Series 8 - 45mm,OS=9.1' | xcpretty && exit ${PIPESTATUS[0]}
