name: Unit tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Watch:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: xcodebuild test -scheme UnitTests -project ElectricSidecar/ElectricSidecar.xcodeproj -destination 'platform=WatchOS Simulator,name=Apple Watch Series 8 (45mm),OS=9.1' | xcpretty && exit ${PIPESTATUS[0]}

  Phone:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: xcodebuild test -scheme UnitTests -project ElectricSidecar/ElectricSidecar.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2' | xcpretty && exit ${PIPESTATUS[0]}
